apply plugin: 'com.android.application'
apply from: '../config.gradle'

android {
    defaultConfig {
        applicationId "com.osfans.font.unicode17"
        minSdk 29
        targetSdk 36
        versionCode 3
        versionName "Plangothic2.9.5795 (2026.7.5) & WenJin2.100(2026.10.2)"
    }

    applicationVariants.configureEach { variant ->
        variant.outputs.configureEach {
            outputFileName = "${applicationId}-${versionName}.APK"
        }
    }
}