name: Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened
      # pull request's head branch was updated
      - synchronize

env:
  CI_NAME: Pull Request CI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Create DB
      run: |
        pushd tools
        python3 -m pip install -r requirements.txt
        touch tables/*.py
        python3 make.py -c
        popd